name: "jaffle_shop"
models:
  - name: customers
    +materialized: table
  - name: stg_customers
    columns:
      - name: CUSTOMER_ID
        tests:
          - not_null
    +materialized: table
  - name: stg_orders
    columns:
      - name: ORDER_ID
        tests:
          - not_null
    +materialized: table
